# Generated by Django 5.2.8 on 2025-11-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_Name', models.CharField(max_length=100)),
                ('Product_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Country_of_Manufacture', models.CharField(max_length=100)),
                ('Date_of_Manfacture', models.DateField()),
                ('Price', models.FloatField()),
                ('Company_Contact_Number', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
